### ISSUE TITLE
被加入Zygisk Denylist/Shamiko的app闪退

### ISSUE THREAD

**Issue by recreationx** [lxgw/advanced-cjk-font-magisk-module-template#1]
Android Version: 12
Device: K20P, SparkOS
Magisk Version: 0c1f6881-alpha (zygisk)
Installed magisk modules:
- Shamiko
- Universal Safetynet Fix
- LSPosed (Zygisk)

在安装字体模块后，字体生效，但所有被加入 zygisk DenyList/被Shamiko屏蔽的模块会闪退。卸载字体模块后一切恢复正常。已排除其他因模块而造成的闪退。

**Comment by lxgw** [comment]
解决方法：

1. 卸载字体模块后重启，用 MT 管理器，将字体模块包中的 EmptyFont 空字体文件 *（位于**模块包中** `/system/fonts` 目录）* 复制到**手机系统**字体文件目录 `/system/fonts`，然后将**手机系统中** `/system/fonts` 目录中的 EmptyFont 空字体文件权限设置为 644。
2. 重新安装字体模块。

红米 Note 5，Derpfest Android 12，将建设银行 APP 在 MagiskHide 中勾选并启用，能够正常使用。应用首先调用的是默认状态下系统字体文件夹中的 EmptyFont 文件，而不是字体模块中的 EmptyFont 文件。

按照 [@拉普拉斯的小恶魔](http://www.coolapk.com/u/1243253) 所说，Magisk Hide 启用后，勾选的应用会在读取 fonts.xml 中所列出的字体文件时因找不到而崩溃。而按照 [@宁静之雨](http://www.coolapk.com/u/55606) 的说法分析，主要是因为模块首先调用的字体 *（默认字体为 Roboto，而 Android 12 内置的是动态可变的 Roboto）* 在默认状态的系统中找不到而发生闪退，那么把 Magisk 模块里首先调用的字体复制到默认状态下手机系统字体目录，使其成为手机默认状态下自带的字体，理论上会解决这个问题。本字体模块模板首先调用 EmptyFont 空字体 *（以往的字体模块模板为 RobotoFake）* ，因而需要在卸载字体模块并重启之后，把 EmptyFont *（或 RobotoFake）* 复制到手机系统字体文件夹。

其他字体模块需要参考系统默认状态下 `/system/etc/fonts.xml` 文件中首先调用的字体，然后需要将首先调用的字体复制手机系统字体文件夹。

**Comment by lxgw** [comment]
可能我的所谓「方法」有点脱裤子放屁——多此一举了，毕竟已经动了 system 分区，干脆回归以往卡刷包的方法直接在 system 分区上替换就完事了（

不过这篇文章主要讲的是用我的「字体模块模板」所做的模块，即使是动 system 分区，也只是复制了几个空字体文件，不需要复制其他字体，也不对系统里自带的字体产生影响，换同样模板制作的模块也不需要再做改动了。当然，这也仅仅是我个人的想法。

**Comment by recreationx** [comment]
在Shamiko v0.2.0里已修复对字体模块崩溃的问题，已成功刷入该模块,和Shamiko一并使用最佳。

**Comment by Neubulae** [comment]
刚用最近的Magisk Alpha，发现好像有冲突？打开Zygisk就无法进入系统，卡启动…
