### ISSUE TITLE
color os 14.0目前字体无法全局

### ISSUE THREAD

**Issue by kinggxlle** [lxgw/advanced-cjk-font-magisk-module-template#17]
rt，一加12按照给出的方法输入后在主要系统界面无法全局。

**Comment by kinggxlle** [comment]
改错了路径

**Comment by fatinghenji** [comment]
能讲一下是怎么做到挂载系统分区可读写的吗？

**Comment by kinggxlle** [comment]
不需要挂载系统分区可读写，直接在这个模块的相应路径里修改就行。

fatinghenji ***@***.***>于2024年3月26日 周二01:37写道：
