### ISSUE TITLE
Redmi K40 使用 PE 12 刷入后, 桌面, Gbroad, 文件选择器 等应用直接崩溃

### ISSUE THREAD

**Issue by zhuhansan666** [lxgw/advanced-cjk-font-magisk-module-template#18]
Redmi K40 使用 PE 12 刷入后, 桌面, Gbroad, 文件选择器 等应用直接崩溃, 删除模块后一切正常
我使用 OTF 格式的 HarmonyOS Sans, 仅替换 en, ei, zh(替换的文件中仅含简体中文)
其他大部分软件正常, 字体替换有效

**Comment by lxgw** [comment]
建议选用其他作者的字体模块模板（或在其他作者已经制作好的刷入后能生效的字体模块基础上替换内部字体文件），恕本人黔驴技穷、爱莫能助。

**Comment by lxgw** [comment]
先安装 Font Loader 模块，如果还不行，建议选用其他作者的字体模块（模板）。

**Comment by zhuhansan666** [comment]
可否给 Font Loader 指个路, 谢谢大佬

**Comment by lxgw** [comment]
> 可否给 Font Loader 指个路, 谢谢大佬

https://github.com/HuskyDG/Zygisk-FontLoader

**Comment by zhuhansan666** [comment]
已解决, 关闭 Magisk SuList 即可解决
