### ISSUE TITLE
一处勘误及一处补充

### ISSUE THREAD

**Issue by akimotoakira** [lxgw/advanced-cjk-font-magisk-module-template#3]
您好，感谢分享，尝试过程中发现两个问题：
1. Readme 中介绍字重的表格里，Thin 和 UltraLight 似乎写反了？应该 UltraLight 是极细，Thin 是纤细才对。
2. 使用方法中有提到“向里面添加 ttf 或 otf 格式的字体文件”，但后文只写了 ttf 的情况，如果使用 otf 格式字体，还需要在 /system/etc/fonts.xml 里将对应需要修改的字体后缀名同步修改成 .otf 才能正常替换生效。

**Comment by lxgw** [comment]
使用 otf 格式的字体直接把文件名改成 *.ttf 就行了（

**Comment by lxgw** [comment]
另外
