### ISSUE TITLE
刷入后为什么不生效呀

### ISSUE THREAD

**Issue by NianBroken** [lxgw/advanced-cjk-font-magisk-module-template#8]
![Screenshot_2022-11-26-15-10-11-807_i pdhe xl ay spv z](https://user-images.githubusercontent.com/57057288/204076902-36ed77b2-5aac-4078-8a9e-b9d560df8eb3.jpg)
![Screenshot_2022-11-26-15-08-12-962_bin mt plus](https://user-images.githubusercontent.com/57057288/204076867-d9f8dd54-eb5f-4155-b41c-f1467d10fca1.jpg)
![Screenshot_2022-11-26-15-08-19-837_bin mt plus](https://user-images.githubusercontent.com/57057288/204076869-bb02698a-3f29-4514-9395-a542593259c3.jpg)
![Screenshot_2022-11-26-15-09-41-963_mark via](https://user-images.githubusercontent.com/57057288/204076879-bbf947b7-efe7-4a08-add1-994df6f31c6f.jpg)

**Comment by lxgw** [comment]
请将扩展名 otf 改为 ttf。
